### ISSUE TITLE
Change package.json so that project can run without global installation of mocha 

### ISSUE THREAD

**Issue by ati-ozgur** [robconery/pg-auth#11]
I propose to change package.json as following.

-- added lines.

```
    "scripts": {
        "start": "node index",
        "test": "mocha test"
    },
 ...
,
    "devDependencies": {
        "mocha": "^2.5.3"
    }

```

this way project will work with following commands even mocha is not globally installed.

```
npm install
npm start
npm test
```

I already made these changes in my fork.

**Comment by robconery** [comment]
And if I use Jasmine?

**Comment by ati-ozgur** [comment]
I don't know about jasmine; but, right now, this project package.json references mocha.
If you have no global installation of mocha, following workflow gives  error.

```
npm install
npm test

> pg-auth@1.0.0 test /your/folder/to/pg-auth
> mocha .

sh: 1: mocha: not found
npm ERR! Test failed.  See above for more details.


```

**Comment by robconery** [comment]
Ahh - true I had forgotten that I included the mocha tests in there :). Care to add this to a PR?
