### ISSUE TITLE
Function get_current_user is pulling fields that don't exist.

### ISSUE THREAD

**Issue by pip-pipkin** [robconery/pg-auth#4]
Hey Rob. I noticed your function get_current_user is pulling fields that don't exist in the members table. Specifically signed in at and profile. I think this is an oversight as the get_current_user function looks to be the same one you used in one of your pluralsight courses.

**Comment by robconery** [comment]
Wow that's odd - hmmm. Thanks for the catch - if you want to PR for the credit please do!
