### ISSUE TITLE
Error when running for the first time

### ISSUE THREAD

**Issue by begriffs** [robconery/pg-auth#9]
Hey I'm excited to discover this project! Trying to use it to add basic auth to a [PostgREST](https://github.com/begriffs/postgrest) API.

I cloned the project and did `npm install` (output [here](https://gist.github.com/begriffs/ba810d7fa82128701a88)) and then tried running it but got this error:

```
$ node index.js
/Users/j/dev/js/pg-auth/index.js:79
    db.run(sql);
      ^
TypeError: Cannot read property 'run' of null
    at /Users/j/dev/js/pg-auth/index.js:79:7
    at /Users/j/dev/js/pg-auth/node_modules/massive/index.js:370:14
    at Object.next (/Users/j/dev/js/pg-auth/node_modules/massive/index.js:105:23)
    at /Users/j/dev/js/pg-auth/node_modules/massive/lib/runner.js:36:12
    at /Users/j/dev/js/pg-auth/node_modules/massive/node_modules/pg/lib/pool.js:80:25
    at /Users/j/dev/js/pg-auth/node_modules/massive/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:274:11
    at /Users/j/dev/js/pg-auth/node_modules/massive/node_modules/pg/lib/pool.js:29:26
    at null.<anonymous> (/Users/j/dev/js/pg-auth/node_modules/massive/node_modules/pg/lib/client.js:176:5)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/j/dev/js/pg-auth/node_modules/massive/node_modules/pg/lib/connection.js:109:12)
```

I'm on a mac running node 0.12 and npm 2.5.1 (installed with nvm).

**Comment by robconery** [comment]
Yay! If your `db` is null it's usually one of a two reasons:
- The db doesn't exists or the connection string is off
- You don't have rights to read the meta stuff

So, check your connection and make sure you have owner rights (needed for the information schema query).

**Comment by robconery** [comment]
Also - did you edit the index.js file to point to your database? That's the `DB` constant at the top.

**Comment by begriffs** [comment]
Ah, easy. Just did `createdb pg_auth` and it all works! Thanks for the quick response.
